version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=airbyte
      - POSTGRES_DB=airbyte
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airbyte"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_config_override.xml:/etc/clickhouse-server/config.d/override.xml
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/9000'"]
      interval: 5s
      timeout: 3s
      retries: 20

  airbyte-server:
    image: airbyte/server:build-b0527c915a-21842-master
    ports:
      - "8000:8000"
    environment:
      - AIRBYTE_VERSION=build-b0527c915a-21842-master
      - DATABASE_URL=jdbc:postgresql://postgres:5432/airbyte
      - DATABASE_USER=airbyte
      - DATABASE_PASSWORD=airbyte
      - WORKSPACE_ROOT=/airbyte/workspace
    volumes:
      - airbyte_workspace:/airbyte/workspace
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  airbyte-webapp:
    image: airbyte/webapp:build-b0527c915a-21842-master
    ports:
      - "8001:80"
    depends_on:
      - airbyte-server

  dagster:
    build:
      context: ./dagster
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dagster:/opt/dagster/app
      - ./dbt:/usr/app/dbt
    environment:
      - DAGSTER_HOME=/opt/dagster/app
      - AIRBYTE_PASSWORD=password
      - DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      airbyte-server:
        condition: service_started

  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    volumes:
      - ./dbt:/usr/app/dbt
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
  postgres_data:
  airbyte_workspace: